### ISSUE TITLE
Missing lxqt_wallet dependency

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/wvdial-gui#1]
There's the following info In the `BUILD_INSTRUCTIONS` file:

> 1. make sure the following packages are installed in your system. Their precise names maybe different in your distribution:
>    
>    a. libqt5-base-devel(or whatever package that ships qt5Core-devel and qt5GUI-devel)
>    b. gcc-c++
>    c. cmake
>    g. pkg-config
>    h. rpmdevtools( this package contains programs necessary to build rpm packages )

I'm building the package on debian and I wasn't able to do it without a library that is provided by `lxqt_wallet` package (it doesn't exists in debian). So I think the info should be updated.

**Comment by mhogomchungu** [comment]
lxqt_wallet is not used in this project and i can not find any mention of it. What error do you get when you try to build?

**Comment by morfikov** [comment]
Actually I had to build the package `lxqt-wallet` in order to get the `liblxqtwallet` library. When I remove it from dependencies, I get the following error:

```
[100%] Linking CXX executable wvdial-gui
/usr/bin/cmake -E cmake_link_script CMakeFiles/wvdial-gui.dir/link.txt --verbose=1
/usr/lib/ccache/c++   -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2    -fPIE -pie -Wl,-z,relro -Wl,-z,now -pie CMakeFiles/wvdial-gui.dir/src/main.cpp.o CMakeFiles/wvdial-gui.dir/src/wvdial.cpp.o CMakeFiles/wvdial-gui.dir/src/moc_wvdial.cpp.o CMakeFiles/wvdial-gui.dir/qrc_icons.cpp.o  -o wvdial-gui -rdynamic -llxqtwallet /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.6.1
/usr/bin/ld: cannot find -llxqtwallet
collect2: error: ld returned 1 exit status
CMakeFiles/wvdial-gui.dir/build.make:192: recipe for target 'wvdial-gui' failed
make[3]: *** [wvdial-gui] Error 1
make[3]: Leaving directory '/build/wvdial-gui-1.0.0~git20160708/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/wvdial-gui.dir/all' failed
make[2]: *** [CMakeFiles/wvdial-gui.dir/all] Error 2
make[2]: Leaving directory '/build/wvdial-gui-1.0.0~git20160708/obj-x86_64-linux-gnu'
Makefile:130: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/build/wvdial-gui-1.0.0~git20160708/obj-x86_64-linux-gnu'
        cd /build/wvdial-gui-1.0.0~git20160708
dh_auto_build: make -j1 returned exit code 2
debian/rules:18: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by mhogomchungu** [comment]
The latest git version should now be build able.

Can you confirm so that i can make a new release with the fix.I took the CMakeLists.txt file from another project of mine and i forgot to remove the lxqtwallet dependency.

**Comment by morfikov** [comment]
Yes, It builds without a problem now.
