### ISSUE TITLE
unusual-interpreter #!xdg-open

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/wvdial-gui#3]
There's the following line in the `wvdial-gui.desktop` file:

`#!/usr/bin/env xdg-open`

Lintian says about it something like this:

```
W: wvdial-gui: unusual-interpreter usr/share/applications/wvdial-gui.desktop #!xdg-open
N:
N:    This package contains a script for an interpreter that is not shipped in
N:    the package and is not known to Lintian. It is possible that there is a
N:    typo or the interpreter is not executable. If not, please file a
N:    wishlist bug against lintian, so it can be added to the list of known
N:    interpreters.
N:
N:    Severity: normal, Certainty: possible
N:
N:    Check: scripts, Type: binary
```

I've checked other `*.desktop` files under the `/usr/share/applications/` directory, but none of them has this kind of a line.

**Comment by mhogomchungu** [comment]
So,what is to do here? remove the line?

Other people are using that line like here: http://unix.stackexchange.com/questions/176035/desktop-file-correct-exec-path

**Comment by mhogomchungu** [comment]
I looked in my system and a handful of .desktop files i looked at did not have it so i will remove it in the next commit.

**Comment by morfikov** [comment]
Here's some info: http://www.linux.org/threads/desktop-entry-files-and-xdg-open.6543/ , but in my system (debian sid) there's no such file that has the line included.
