### ISSUE TITLE
Configuration does not specify a valid login name/password

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/wvdial-gui#4]
I was unable to connect using `wvdial-gui`. Here's to log:

```
--> WvDial: Internet dialer version 1.61
--> Cannot set information for serial port.
--> Initializing modem.
--> Sending: ATZ
ATZ
OK
--> Sending: ATQ0 V1 E1 H0 S0=0
ATQ0 V1 E1 H0 S0=0
OK
--> Modem initialized.
--> Configuration does not specify a valid login name.
--> Configuration does not specify a valid password.
```

What login and password is it asking about?

**Comment by mhogomchungu** [comment]
Can you make a data connection when running "wvdial" from the terminal?,the application assumes "wvdial" is self sufficient and does not pass it any arguments.

my "/etc/wvdial.conf" looks like below:

try adding bogus username and password entries to silence the error.They will not be used if your service provider does not require them.

```
[Dialer Defaults]
Init2 = ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
Modem Type = USB Modem
; Phone = <Target Phone Number>
ISDN = 0
; Username = <Your Login Name>
Init1 = ATZ
; Password = <Your Password>
Modem = /dev/ttyACM0
Baud = 460800
Phone = *99#
Password = "Vodafone"
Username = "Vodafone"
```

**Comment by morfikov** [comment]
> Can you make a data connection when running "wvdial" from the terminal?

Yes, but I have to use commands like the one below:

`$ wvdial modem-start set-new red_bull_mobile-auto`

Check my config file: https://github.com/morfikov/files/blob/master/configs/etc/wvdial.conf .

**Comment by mhogomchungu** [comment]
Did it work when adding bogus username and password in your config file?

**Comment by morfikov** [comment]
I just added:

```
Password = "Vodafone"
Username = "Vodafone"
```

And It worked:

```
--> WvDial: Internet dialer version 1.61
--> Cannot set information for serial port.
--> Initializing modem.
--> Sending: ATZ
ATZ
OK
--> Sending: ATQ0 V1 E1 H0 S0=0
ATQ0 V1 E1 H0 S0=0
OK
--> Modem initialized.
--> Sending: ATDT*99#
--> Waiting for carrier.
ATDT*99#
CONNECT
--> Carrier detected.  Starting PPP immediately.
--> Starting pppd at Sun Jul 10 17:21:20 2016
--> Warning: Could not modify /etc/ppp/pap-secrets: Permission denied
--> --> PAP (Password Authentication Protocol) may be flaky.
--> Warning: Could not modify /etc/ppp/chap-secrets: Permission denied
--> --> CHAP (Challenge Handshake) may be flaky.
--> Pid of pppd: 130203
--> Using interface ppp0
--> Authentication (PAP) started
--> Authentication (PAP) successful
--> local  IP address 10.139.166.221
--> remote IP address 10.64.64.64
--> Script /etc/ppp/ip-up run successful
--> Default route Ok.
--> Nameserver (DNS) Ok.
--> Connected... Press Ctrl-C to disconnect
```

But how does it know which profile to use in order to connect?

**Comment by morfikov** [comment]
I think it takes parameters from the last connection. I mean when I connect manually via `wvdial`, then the parameters will be used by `wvdial-gui`. Is there a way to choose which settings will be used or am I forced to change that via `wvdial`?

**Comment by mhogomchungu** [comment]
wvdial-gui currently calls wvdial with no arguments meaning wvdial takes its configuration options from its default locations which are "/etc/wvdial.config" and "$HOME/.wvdialrc"(this is according to wvdial documentation).

The idea i had is that wvdial-gui will work if wvdial also works without any additional arguments.

**Comment by mhogomchungu** [comment]
I am closing this one since the problem you had is now gone after you added those options.
