### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/wvdial-gui#5]
The log in the window is scrolled automatically to the top when some new lines appear in it. I think it would be better to "scroll to the bottom" with new lines, and cancel scrolling when a user scrolls up a little bit, so he could freely check the log, like in terminals.

**Comment by mhogomchungu** [comment]
the text field now automatically scroll to the bottom when new text is added.

I do not think its possible to stop this behavior when a user manually moves the scroll bar up/down.
